# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' tour_superSimple
#'
#' @param n an integer
#' @return nothing interesting... cities from 1 to n
#' @export
tour_superSimple <- function(n) {
    .Call(`_TSP_tour_superSimple`, n)
}

